# Generated by Django 5.2.3 on 2025-06-23 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTVChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='series/default.jpg', upload_to='series/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('series', models.CharField(choices=[('ME', 'Mea'), ('MP', 'My Little Pony'), ('PP', 'Peppa Pig'), ('SF', 'Sofia the First'), ('PW', 'Paw Patrol')], max_length=2)),
            ],
        ),
    ]
